---
# Passenger repository setup.
- name: Nginx Install | setup passenger repository
  yum_repository:
    name: passenger
    description: passenger repository
    baseurl: 'https://oss-binaries.phusionpassenger.com/yum/passenger/el/$releasever/$basearch'
    gpgkey: 'https://packagecloud.io/gpg.key'
    repo_gpgcheck: yes
    gpgcheck: no
    enabled: yes
    sslverify: yes
    sslcacert: '/etc/pki/tls/certs/ca-bundle.crt'

- name: Nginx Install | setup passenger-source repository
  yum_repository:
    name: passenger-source
    description: passenger source repository
    baseurl: 'https://oss-binaries.phusionpassenger.com/yum/passenger/el/$releasever/SRPMS'
    gpgkey: 'https://packagecloud.io/gpg.key'
    repo_gpgcheck: yes
    gpgcheck: no
    enabled: yes
    sslverify: yes
    sslcacert: '/etc/pki/tls/certs/ca-bundle.crt'

# Install passenger and things
- name: Nginx Install | install packages
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
    - pygpgme
    - curl
    - nginx
    - passenger
    - passenger-devel

# Ensure sites directories exist, placed here to avoid duplication
- name: Nginx Install | create /etc/nginx/{sites-available sites-enabled}
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
  with_items:
    - '/etc/nginx/sites-available'
    - '/etc/nginx/sites-enabled'
