---
# Setup the variables to be used by the different tasks
- include: variable_setup.yml

# Include OS-specific installation tasks.
- include: "install_{{ ansible_os_family }}.yml"

# configure nginx and passenger
- include: configure.yml

# do the needful with respect to the nginx service
- include: service.yml
